server:
  port: 8888
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/postgres?currentSchema=public
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate