server:
  port: 8686

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres?currentSchema=public
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate